import { CategoryGroup } from '@/types/category';

export const FOOD_CATEGORIES = [
  { label: 'Gluten', value: 0 },
  { label: 'Peanuts', value: 1 },
  { label: 'Eggs', value: 2 },
  { label: 'Fish', value: 3 },
  { label: 'Tree Nuts', value: 4 },
  { label: 'Dairy', value: 5 },
  { label: 'Soy', value: 6 },
  { label: 'Shellfish', value: 7 },
  { label: 'Milk', value: 8 },
  { label: 'Cream', value: 9 },
  { label: 'Cheese', value: 10 },
  { label: 'Yogurt', value: 11 },
  { label: 'Cottage Cheese', value: 12 },
  { label: 'Whey Powder', value: 13 },
  { label: 'Grains', value: 14 },
  { label: 'Breakfast Cereals', value: 15 },
  { label: 'Pastas', value: 16 },
  { label: 'Breads', value: 17 },
  { label: 'Rice', value: 18 },
  { label: 'Oatmeal', value: 19 },
  { label: 'Sugar', value: 20 },
  { label: 'Tofu', value: 21 },
  { label: 'Soy Milk', value: 22 },
  { label: 'Red Meat', value: 23 },
  { label: 'Beef', value: 24 },
  { label: 'Pork/Bacon', value: 25 },
  { label: 'Lamb', value: 26 },
  { label: 'Veal', value: 27 },
  { label: 'Poultry', value: 28 },
  { label: 'Chicken', value: 29 },
  { label: 'Turkey', value: 30 },
  { label: 'Salmon', value: 31 },
  { label: 'Tuna', value: 32 },
  { label: 'Tilapia', value: 33 },
  { label: 'Sardines', value: 34 },
  { label: 'Trout & Snapper', value: 35 },
  { label: 'Mayo', value: 36 },
  { label: 'Fats & Nuts', value: 37 },
  { label: 'Avocado', value: 38 },
  { label: 'Almonds', value: 39 },
  { label: 'Walnuts', value: 40 },
  { label: 'Pecans', value: 41 },
  { label: 'Legumes', value: 42 },
  { label: 'Beans', value: 43 },
  { label: 'Lentils', value: 44 },
  { label: 'Peas', value: 45 },
  { label: 'Fruits', value: 46 },
  { label: 'Apple', value: 47 },
  { label: 'Banana', value: 48 },
  { label: 'Grapes', value: 49 },
  { label: 'Orange', value: 50 },
  { label: 'Strawberries', value: 51 },
  { label: 'Raspberries', value: 52 },
  { label: 'Blueberries', value: 53 },
  { label: 'Fruit Juice', value: 54 },
  { label: 'Vegetables', value: 55 },
  { label: 'Artichoke', value: 56 },
  { label: 'Asparagus', value: 57 },
  { label: 'Beets', value: 58 },
  { label: 'Broccoli', value: 59 },
  { label: 'Carrots', value: 60 },
  { label: 'Sprouts', value: 61 },
  { label: 'Celery', value: 62 },
  { label: 'Peppers', value: 63 },
  { label: 'Tomato', value: 64 },
  { label: 'Eggplant', value: 65 },
  { label: 'Starchy Vegetables', value: 66 },
  { label: 'Potatoes & Yams', value: 67 },
  { label: 'Corn', value: 68 },
  { label: 'Honey', value: 69 },
  { label: 'Spices and Herbs', value: 70 },
  { label: 'Baby Foods', value: 71 },
  { label: 'Soups, Sauces, and Gravies', value: 72 },
  { label: 'Sausages and Luncheon Meats', value: 73 },
  { label: 'Beverages', value: 74 },
  { label: 'Baked Products', value: 75 },
  { label: 'Sweets', value: 76 },
  { label: 'Fast Foods', value: 77 },
  { label: 'Ethnic Foods', value: 78 },
  { label: 'Supplements', value: 79 },
] as const;

export const CATEGORIES_BY_GROUP: CategoryGroup = [
  {
    group: 'Common Exclusions',
    mainItem: undefined,
    items: [0, 1, 2, 3, 4, 5, 6, 7],
  },
  {
    group: 'Dairy',
    mainItem: 5,
    items: [8, 9, 10, 11, 12, 13],
  },
  {
    group: 'Eggs',
    mainItem: undefined,
    items: [2],
  },
  {
    group: 'Grains',
    mainItem: 14,
    items: [15, 16, 17, 18, 19, 20],
  },
  {
    group: 'Soy',
    mainItem: 6,
    items: [21, 22],
  },
  {
    group: 'Red Meat',
    mainItem: 23,
    items: [24, 25, 26, 27],
  },
  {
    group: 'Poultry',
    mainItem: 28,
    items: [29, 30],
  },
  {
    group: 'Fish',
    mainItem: 3,
    items: [31, 32, 33, 34, 35],
  },
  {
    group: 'Shellfish',
    mainItem: undefined,
    items: [7],
  },
  {
    group: 'Mayo',
    mainItem: undefined,
    items: [36],
  },
  {
    group: 'Fats & Nuts',
    mainItem: 37,
    items: [38, 39, 40, 41],
  },
  {
    group: 'Legumes',
    mainItem: 42,
    items: [43, 44, 45],
  },
  {
    group: 'Fruits',
    mainItem: 46,
    items: [47, 48, 49, 50, 51, 52, 53],
  },
  {
    group: 'Fruit Juice',
    mainItem: undefined,
    items: [54],
  },
  {
    group: 'Vegetables',
    mainItem: 55,
    items: [56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
  },
  {
    group: 'Starchy Vegetables',
    mainItem: 66,
    items: [67, 68],
  },
  {
    group: 'Honey',
    mainItem: undefined,
    items: [69],
  },
  {
    group: 'More',
    mainItem: undefined,
    items: [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
  },
] as const;

export const MAIN_ITEM_CATEGORIES = CATEGORIES_BY_GROUP.reduce<Set<number>>(
  (mainItemSet, category) => {
    if (category.mainItem !== undefined) {
      mainItemSet.add(category.mainItem);
    }
    return mainItemSet;
  },
  new Set<number>(),
);

export const EXCLUDED_BY_DIET = {
  anything: [],
  keto: [14, 42, 66, 55],
  mediterranean: [23, 54, 66],
  paleo: [5, 14, 43, 6, 67],
  vegan: [23, 28, 3, 7, 5, 2, 36, 69],
  vegetarian: [23, 28, 3, 7],
};
