export const PATH = {
  ADMIN: '/admin',
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  UNAUTHORIZED: '/unauthorized',
  TERMS_OF_SERVICE: '/terms-of-service',
  HOW_IT_WORKS: '/how-it-works',
  WHY_NUTRIPLAN: '/why-nutri-plan',
  FAQS: '/faqs',
  BECOME_CHEF: '/become-a-chef',
  CAREERS: '/careers',
  DELIVERY_MAP: '/delivery-map',
  GIFT_CARD: '/gift-card',
  SUSTAINABILITY: '/sustainability',
  SPECIAL_LINES: '/special-lines',
  CLEAN_LINE: '/clean-line',
  BLOG: '/blog',
  BROWSE_FOODS: '/browser-foods',
  SUPPORTED_DIETS: '/supported-diets',
  FOR_PROFESSIONALS: '/for-professionals',
  ABOUT_US: '/about-us',
} as const;
