export const PATH = {
  ADMIN: '/admin',
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  UNAUTHORIZED: '/unauthorized',
  TERMS_OF_SERVICE: '/terms-of-service',
  HOW_IT_WORKS: '/how-it-works',
  WHY_NUTRIPLAN: '/why-nutri-plan',
  FAQS: '/faqs',
  BECOME_CHEF: '/become-a-chef',
  CAREERS: '/careers',
  DELIVERY_MAP: '/delivery-map',
  GIFT_CARD: '/gift-card',
  SUSTAINABILITY: '/sustainability',
  SPECIAL_LINES: '/special-lines',
  CLEAN_LINE: '/clean-line',
  BLOG: '/blog',
  BROWSE_FOODS: '/browse-foods',
  SUPPORTED_DIETS: '/supported-diets',
  FOR_PROFESSIONALS: '/for-professionals',
  ABOUT_US: '/about-us',
  MEAL_PLAN: '/meal-plan',

  GROCERIES: '/groceries',
  DISCOVER: '/discover',
  CUSTOM_RECIPES: '/custom-recipes',
  COLLECTIONS: '/collections',
  COLLECTION_ID: '/collections/$id',
  SAVED_PLANS: '/saved-plans',

  DIET_NUTRITION: '/diet-nutrition',
  NUTRITION_TARGETS: '/nutrition-targets',
  PRIMARY_DIET: '/primary-diet',
  FOOD_EXCLUSIONS: '/food-exclusions',
  RATED_FOODS: '/rated-foods',

  MEALS_SCHEDULE: '/meals-schedule',
  MEAL_SETTINGS: '/meal-settings',
  LEFTOVERS: '/leftovers',

  PHYSICAL_STATS: '/physical-stats',
  WEIGHT_GOAL: '/weight-goal',

  ACCOUNT: '/account',

  LOGOUT: '/logout',
  CREATE_COLLECTION: '/collections/create',
} as const;
