/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WeightGoalIndexImport } from './routes/weight-goal/index'
import { Route as UnauthorizedIndexImport } from './routes/unauthorized/index'
import { Route as RegisterIndexImport } from './routes/register/index'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as PhysicalStatsIndexImport } from './routes/physical-stats/index'
import { Route as NutritionTargetsIndexImport } from './routes/nutrition-targets/index'
import { Route as MealPlanIndexImport } from './routes/meal-plan/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as CollectionsIndexImport } from './routes/collections/index'
import { Route as BrowseFoodsIndexImport } from './routes/browse-foods/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as CollectionsIdImport } from './routes/collections/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WeightGoalIndexRoute = WeightGoalIndexImport.update({
  id: '/weight-goal/',
  path: '/weight-goal/',
  getParentRoute: () => rootRoute,
} as any)

const UnauthorizedIndexRoute = UnauthorizedIndexImport.update({
  id: '/unauthorized/',
  path: '/unauthorized/',
  getParentRoute: () => rootRoute,
} as any)

const RegisterIndexRoute = RegisterIndexImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any)

const PhysicalStatsIndexRoute = PhysicalStatsIndexImport.update({
  id: '/physical-stats/',
  path: '/physical-stats/',
  getParentRoute: () => rootRoute,
} as any)

const NutritionTargetsIndexRoute = NutritionTargetsIndexImport.update({
  id: '/nutrition-targets/',
  path: '/nutrition-targets/',
  getParentRoute: () => rootRoute,
} as any)

const MealPlanIndexRoute = MealPlanIndexImport.update({
  id: '/meal-plan/',
  path: '/meal-plan/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const CollectionsIndexRoute = CollectionsIndexImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRoute,
} as any)

const BrowseFoodsIndexRoute = BrowseFoodsIndexImport.update({
  id: '/browse-foods/',
  path: '/browse-foods/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const CollectionsIdRoute = CollectionsIdImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/browse-foods/': {
      id: '/browse-foods/'
      path: '/browse-foods'
      fullPath: '/browse-foods'
      preLoaderRoute: typeof BrowseFoodsIndexImport
      parentRoute: typeof rootRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/meal-plan/': {
      id: '/meal-plan/'
      path: '/meal-plan'
      fullPath: '/meal-plan'
      preLoaderRoute: typeof MealPlanIndexImport
      parentRoute: typeof rootRoute
    }
    '/nutrition-targets/': {
      id: '/nutrition-targets/'
      path: '/nutrition-targets'
      fullPath: '/nutrition-targets'
      preLoaderRoute: typeof NutritionTargetsIndexImport
      parentRoute: typeof rootRoute
    }
    '/physical-stats/': {
      id: '/physical-stats/'
      path: '/physical-stats'
      fullPath: '/physical-stats'
      preLoaderRoute: typeof PhysicalStatsIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/unauthorized/': {
      id: '/unauthorized/'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedIndexImport
      parentRoute: typeof rootRoute
    }
    '/weight-goal/': {
      id: '/weight-goal/'
      path: '/weight-goal'
      fullPath: '/weight-goal'
      preLoaderRoute: typeof WeightGoalIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/admin': typeof AdminIndexRoute
  '/browse-foods': typeof BrowseFoodsIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/login': typeof LoginIndexRoute
  '/meal-plan': typeof MealPlanIndexRoute
  '/nutrition-targets': typeof NutritionTargetsIndexRoute
  '/physical-stats': typeof PhysicalStatsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/register': typeof RegisterIndexRoute
  '/unauthorized': typeof UnauthorizedIndexRoute
  '/weight-goal': typeof WeightGoalIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/admin': typeof AdminIndexRoute
  '/browse-foods': typeof BrowseFoodsIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/login': typeof LoginIndexRoute
  '/meal-plan': typeof MealPlanIndexRoute
  '/nutrition-targets': typeof NutritionTargetsIndexRoute
  '/physical-stats': typeof PhysicalStatsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/register': typeof RegisterIndexRoute
  '/unauthorized': typeof UnauthorizedIndexRoute
  '/weight-goal': typeof WeightGoalIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/browse-foods/': typeof BrowseFoodsIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/meal-plan/': typeof MealPlanIndexRoute
  '/nutrition-targets/': typeof NutritionTargetsIndexRoute
  '/physical-stats/': typeof PhysicalStatsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/unauthorized/': typeof UnauthorizedIndexRoute
  '/weight-goal/': typeof WeightGoalIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections/$id'
    | '/admin'
    | '/browse-foods'
    | '/collections'
    | '/login'
    | '/meal-plan'
    | '/nutrition-targets'
    | '/physical-stats'
    | '/profile'
    | '/register'
    | '/unauthorized'
    | '/weight-goal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections/$id'
    | '/admin'
    | '/browse-foods'
    | '/collections'
    | '/login'
    | '/meal-plan'
    | '/nutrition-targets'
    | '/physical-stats'
    | '/profile'
    | '/register'
    | '/unauthorized'
    | '/weight-goal'
  id:
    | '__root__'
    | '/'
    | '/collections/$id'
    | '/admin/'
    | '/browse-foods/'
    | '/collections/'
    | '/login/'
    | '/meal-plan/'
    | '/nutrition-targets/'
    | '/physical-stats/'
    | '/profile/'
    | '/register/'
    | '/unauthorized/'
    | '/weight-goal/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsIdRoute: typeof CollectionsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BrowseFoodsIndexRoute: typeof BrowseFoodsIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MealPlanIndexRoute: typeof MealPlanIndexRoute
  NutritionTargetsIndexRoute: typeof NutritionTargetsIndexRoute
  PhysicalStatsIndexRoute: typeof PhysicalStatsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  UnauthorizedIndexRoute: typeof UnauthorizedIndexRoute
  WeightGoalIndexRoute: typeof WeightGoalIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsIdRoute: CollectionsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  BrowseFoodsIndexRoute: BrowseFoodsIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MealPlanIndexRoute: MealPlanIndexRoute,
  NutritionTargetsIndexRoute: NutritionTargetsIndexRoute,
  PhysicalStatsIndexRoute: PhysicalStatsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  UnauthorizedIndexRoute: UnauthorizedIndexRoute,
  WeightGoalIndexRoute: WeightGoalIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/collections/$id",
        "/admin/",
        "/browse-foods/",
        "/collections/",
        "/login/",
        "/meal-plan/",
        "/nutrition-targets/",
        "/physical-stats/",
        "/profile/",
        "/register/",
        "/unauthorized/",
        "/weight-goal/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/collections/$id": {
      "filePath": "collections/$id.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx"
    },
    "/browse-foods/": {
      "filePath": "browse-foods/index.tsx"
    },
    "/collections/": {
      "filePath": "collections/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/meal-plan/": {
      "filePath": "meal-plan/index.tsx"
    },
    "/nutrition-targets/": {
      "filePath": "nutrition-targets/index.tsx"
    },
    "/physical-stats/": {
      "filePath": "physical-stats/index.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.tsx"
    },
    "/register/": {
      "filePath": "register/index.tsx"
    },
    "/unauthorized/": {
      "filePath": "unauthorized/index.tsx"
    },
    "/weight-goal/": {
      "filePath": "weight-goal/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
